name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: dev
    env:
      # Azure credentials for Terraform provider using OIDC
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true

      # Sensitive Terraform variables from GitHub Secrets
      TF_VAR_azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
      # Add other sensitive TF_VAR_ variables here if needed
      TF_VAR_cosmosdb_key: ${{ secrets.COSMOSDB_PRIMARY_KEY }}

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.12.2"

      # 3️⃣ Terraform init
      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      # 4️⃣ Terraform plan
      - name: Terraform Plan
        working-directory: ./infra
        run: terraform plan -out=tfplan -var-file="main.tfvars.json" -compact-warnings

      # 5️⃣ Terraform apply
      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -auto-approve tfplan
