name: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: dev
    env:

      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true

      # Sensitive Terraform variables
      TF_VAR_azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
      TF_VAR_vnet_name: ${{ secrets.VNET_NAME }}
      TF_VAR_vnet_resource_group_name: ${{ secrets.VNET_RESOURCE_GROUP_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.12.2"

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Import Existing Resources
        working-directory: ./infra
        run: |
          # Import App Service Plan
          terraform import module.backend.azurerm_service_plan.backend "/subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/pen-match-api-v2/providers/Microsoft.Web/serverFarms/pen-match-api-v2-app-backend-asp" || true
          
          # Import Network Security Groups
          terraform import module.network.azurerm_network_security_group.privateendpoints "/subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/$TF_VAR_vnet_resource_group_name/providers/Microsoft.Network/networkSecurityGroups/pen-match-api-v2-pe-nsg" || true
          
          terraform import module.network.azurerm_network_security_group.app_service "/subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/$TF_VAR_vnet_resource_group_name/providers/Microsoft.Network/networkSecurityGroups/pen-match-api-v2-as-nsg" || true
          
          terraform import module.network.azurerm_network_security_group.web "/subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/$TF_VAR_vnet_resource_group_name/providers/Microsoft.Network/networkSecurityGroups/pen-match-api-v2-web-nsg" || true
          
          terraform import module.network.azurerm_network_security_group.container_instance "/subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/$TF_VAR_vnet_resource_group_name/providers/Microsoft.Network/networkSecurityGroups/pen-match-api-v2-ci-nsg" || true


      - name: Terraform Plan
        working-directory: ./infra
        run: 
          terraform plan -var-file="main.tfvars.json" -compact-warnings
          terraform apply -auto-approve -var-file="main.tfvars.json"

