name: Test Cosmos DB Connection via App Service

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-cosmos-connection:
    name: Test Cosmos DB Connection
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 10
    
    env:
      AZURE_WEBAPP_NAME: 'pen-match-api-v2-app'
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure App Service for Cosmos Test
        run: |
          az webapp config appsettings set \
            --resource-group $RESOURCE_GROUP_NAME \
            --name $AZURE_WEBAPP_NAME \
            --settings \
              AZURE_COSMOSDB_ENDPOINT="${{ secrets.AZURE_COSMOSDB_ENDPOINT }}"

      - name: Trigger App Service Deployment
        run: |
          az webapp deployment source sync \
            --resource-group $RESOURCE_GROUP_NAME \
            --name $AZURE_WEBAPP_NAME

      - name: Set Startup Command for Testing
        run: |
          az webapp config set \
            --resource-group $RESOURCE_GROUP_NAME \
            --name $AZURE_WEBAPP_NAME \
            --startup-file "python app/cosmos.py"

      - name: Wait for Deployment
        run: sleep 90

      - name: Restart and Test
        run: |
          az webapp restart \
            --resource-group $RESOURCE_GROUP_NAME \
            --name $AZURE_WEBAPP_NAME
          sleep 60

      - name: Get Application Logs
        run: |
          az webapp log tail \
            --resource-group $RESOURCE_GROUP_NAME \
            --name $AZURE_WEBAPP_NAME \
            --provider application

      - name: Get All Logs (Alternative)
        run: |
          az webapp log download \
            --resource-group $RESOURCE_GROUP_NAME \
            --name $AZURE_WEBAPP_NAME \
            --log-file cosmos-test-logs.zip
          unzip -l cosmos-test-logs.zip

      - name: Restore Original Startup Command
        run: |
          az webapp config set \
            --resource-group $RESOURCE_GROUP_NAME \
            --name $AZURE_WEBAPP_NAME \
            --startup-file "gunicorn --bind=0.0.0.0 --timeout 600 app:app"

      - name: Azure Logout
        run: az logout
        if: always()