name: Test Cosmos DB Connection via App Service

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-cosmos-connection:
    name: Test Cosmos DB Connection
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 10
    
    env:
      AZURE_WEBAPP_NAME: 'pen-match-api-v2-app'
      AZURE_WEBAPP_PACKAGE_PATH: '.'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure App Service for Cosmos Test
        run: |
          echo "⚙️ Setting environment variables..."
          az webapp config appsettings set \
            --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --settings \
              AZURE_COSMOSDB_ENDPOINT="${{ secrets.AZURE_COSMOSDB_ENDPOINT }}"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Test Cosmos DB via App Service Logs
        run: |
          echo "⏳ Waiting for deployment..."
          sleep 60
          
          echo "🧪 Testing Cosmos DB connection..."
          
          # Run cosmos test via Azure CLI
          az webapp ssh \
            --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --command "cd /home/site/wwwroot && python app/cosmos.py" \
          || echo "SSH not available, checking logs..."
          
          # Alternative: Check logs
          az webapp log tail \
            --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --timeout 30

      - name: Azure Logout
        run: az logout
        if: always()