name: Deploy and Test Web App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'pen-match-api-v2-app'  # Replace with your actual web app name
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.13'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Azure Login using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Run Simple Test
      run: |
        echo "Running test to verify deployment workflow..."
        python app/test_app.py
        echo "Test completed successfully!"

    - name: Azure Logout
      run: |
        az logout
      if: always()