name: Test Cosmos DB Connection via App Service

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'app/cosmos.py'
      - '.github/workflows/test-cosmos.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-cosmos-connection:
    name: Test Cosmos DB Connection
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 10
    
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      APP_SERVICE_NAME: ${{ secrets.APP_SERVICE_NAME }}
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install azure-cosmos azure-identity

      - name: Prepare Deployment Package
        run: |
          echo "📦 Preparing cosmos test package..."
          mkdir -p deployment
          cp app/cosmos.py deployment/
          echo "azure-cosmos>=4.5.0" > deployment/requirements.txt
          echo "azure-identity>=1.15.0" >> deployment/requirements.txt
          echo "python cosmos.py" > deployment/startup.txt

      - name: Deploy Test to App Service
        run: |
          echo "🚀 Deploying cosmos test to App Service..."
          cd deployment
          zip -r ../deployment.zip .
          cd ..
          
          az webapp deployment source config-zip \
            --resource-group $RESOURCE_GROUP_NAME \
            --name $APP_SERVICE_NAME \
            --src deployment.zip

      - name: Configure App Service Environment
        run: |
          echo "⚙️ Setting Cosmos DB environment variables..."
          az webapp config appsettings set \
            --resource-group $RESOURCE_GROUP_NAME \
            --name $APP_SERVICE_NAME \
            --settings \
              AZURE_COSMOSDB_ENDPOINT="${{ secrets.AZURE_COSMOSDB_ENDPOINT }}" \
              SCM_DO_BUILD_DURING_DEPLOYMENT=true

      - name: Run Cosmos DB Test
        run: |
          echo "🧪 Running Cosmos DB connection test..."
          sleep 30  # Wait for deployment
          
          # Execute the test on App Service
          RESULT=$(az webapp ssh --resource-group $RESOURCE_GROUP_NAME \
            --name $APP_SERVICE_NAME \
            --command "cd /home/site/wwwroot && python cosmos.py" 2>&1)
          
          echo "Test Result:"
          echo "$RESULT"
          
          if [[ "$RESULT" == *"✅ Connected!"* ]]; then
            echo "✅ Cosmos DB connection test PASSED"
          else
            echo "❌ Cosmos DB connection test FAILED"
            exit 1
          fi